#ifndef APPLICATION_CORE_GLOBAL_H
#define APPLICATION_CORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(APPLICATION_CORE_LIBRARY)
#define APPLICATION_CORE_EXPORT Q_DECL_EXPORT
#else
#define APPLICATION_CORE_EXPORT Q_DECL_IMPORT
#endif

#endif // APPLICATION_CORE_GLOBAL_H
